/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PtWidget {
    'class': string;
    'height': string;
    'strategy': string;
  }
  interface PtWidgetPage {
    'chartId': string;
    'class': string;
    'height': string;
    'strategy': string;
  }
}

declare global {


  interface HTMLPtWidgetElement extends Components.PtWidget, HTMLStencilElement {}
  var HTMLPtWidgetElement: {
    prototype: HTMLPtWidgetElement;
    new (): HTMLPtWidgetElement;
  };

  interface HTMLPtWidgetPageElement extends Components.PtWidgetPage, HTMLStencilElement {}
  var HTMLPtWidgetPageElement: {
    prototype: HTMLPtWidgetPageElement;
    new (): HTMLPtWidgetPageElement;
  };
  interface HTMLElementTagNameMap {
    'pt-widget': HTMLPtWidgetElement;
    'pt-widget-page': HTMLPtWidgetPageElement;
  }
}

declare namespace LocalJSX {
  interface PtWidget extends JSXBase.HTMLAttributes<HTMLPtWidgetElement> {
    'class'?: string;
    'height'?: string;
    'strategy'?: string;
  }
  interface PtWidgetPage extends JSXBase.HTMLAttributes<HTMLPtWidgetPageElement> {
    'chartId'?: string;
    'class'?: string;
    'height'?: string;
    'strategy'?: string;
  }

  interface IntrinsicElements {
    'pt-widget': PtWidget;
    'pt-widget-page': PtWidgetPage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


